name: Daily Adidas Price Tracking

on:
  schedule:
    - cron: "0 8 * * *" # Runs every day at 8 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install gspread google-auth requests beautifulsoup4
      - name: Write credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | perl -pe 's/\\n/\n/g' > credentials.json
      - name: Show credentials file (DEBUG)
        run: cat credentials.json
      - name: Run price tracker
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python track_adidas_prices.py
