name: Daily Adidas Price Tracking

#on:
#  schedule:
#    - cron: "0 8 * * *" # Runs every day at 8 AM UTC
#  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/608211164396/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'sa-pricetracker-sheetsapi@pricetracker-461517.iam.gserviceaccount.com'
      - name: Install dependencies
        run: pip install gspread google-auth requests beautifulsoup4
      - name: Run price tracker
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python track_adidas_prices.py
